### ISSUE TITLE
What if the card type is unknown by the payment app?

### ISSUE THREAD

**Issue by tommythorsen** [w3c/webpayments-methods-card#19]
I've been playing around with making a proof-of-concept payment app that does basic card payment, and one issue I've run into is that it's not trivial to know the type of a card. This means that it's hard for the payment app to behave correctly, if the payee passes a list of card types in `BasicCardRequest.supportedTypes`.

Dealing with `BasicCardRequest.supportedNetworks` is relatively trivial, as the network can be trivially deduced from the card number. The card type, however is hard to deduce without resorting to keeping a complete database of IINs (like the one that can be found here: [https://github.com/binlist/data](https://github.com/binlist/data)). That's a solution I'd rather not do, as it's hard to keep this list of IINs complete and up-to-date.

Another solution could be to have the user select the type of card from a drop-down list. This would probably work, at least in the cases where the user does not pick the wrong type. It is, however, quite uncommon to have a field like this in a card credential input form, so it creates a little bit of added friction between the user-agent and the user, that I'd rather avoid if I could.

Is the `BasicCardRequest.supportedTypes` absolutely necessary? Could we cut it from the specification? If not, could we specify what happens if the type for a card is unknown?

**Comment by webpayments-specs** [comment]
Keep in mind this becomes an issue only when the merchant specifies
something like "visa/debit" as the payment method. Chrome currently has no
way of matching this payment method, for example. However, it is possible
in principle.

If the merchant specifies something like "visa" payment method, then simple
network detection will work.

On Nov 1, 2016 5:53 AM, "Tommy Thorsen" notifications@github.com wrote:

I've been playing around with making a proof-of-concept payment app that
does basic card payment, and one issue I've run into is that it's not
trivial to know the type of a card. This means that it's hard for the
payment app to behave correctly, if the payee passes a list of card types
in BasicCardRequest.supportedTypes.

The dealing with BasicCardRequest.supportedNetworks is relatively trivial,
as the network can be trivially deduced from the card number. The card
type, however is hard to deduce without resorting to keeping a complete
database of IINs (like the one that can be found here:
https://github.com/binlist/data). That's a solution I'd rather not do, as
it's hard to keep this list of IINs complete and up-to-date.

Another solution could be to have the user select the type of card from a
drop-down list. This would probably work, at least in the cases where the
user does not pick the wrong type. It is, however, quite uncommon to have a
field like this in a card credential input form, so it creates a little bit
of added friction between the user-agent and the user, that I'd rather
avoid if I could.

Is the BasicCardRequest.supportedTypes absolutely necessary? Could we cut
it from the specification? If not, could we specify what happens if the
type for a card is unknown?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/w3c/webpayments-methods-card/issues/19, or mute the
thread

**Comment by webpayments-specs** [comment]
By the way, I don't think card type should be removed. Card network
detection is sufficient for a simple implementation. Card type detection
can be added later.

**Comment by tommythorsen** [comment]
@rsolomakhin said:

> Keep in mind this becomes an issue only when the merchant specifies something like "visa/debit" as the payment method.

In the latest editor's draft of the specification, I see that these payment methods have been replaced with the single `basic-card` payment method. The `visa` and `debit` parts are moved into the method specific data section. Personally, I think this is a great improvement, and it makes my implementation much tidier than before.

@rsolomakhin said:

> By the way, I don't think card type should be removed.

If this field is in the specification, I feel it's important that merchants can trust that it will work. If most basic card payment apps ignore this field, because it is tricky to implement, then we could get into the situation where merchants too will stay away from using this field, since it usually does not work. Then we end up with a piece of specification that nobody uses, which is not very cool.

**Comment by zkoch** [comment]
@tommythorsen given that we've made the move to basic-card, are you comfortable with us closing this issue?

**Comment by tommythorsen** [comment]
Sure.
