### ISSUE TITLE
Clarify this specification is intended to become a W3C Note

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-methods-card#27]
It is my understanding this spec is intended to become a W3C Note (and that the WPWG has the same intentions for other payment method specs). The status section does not indicate clearly that this spec is NOT expected to become a recommendation.

**Comment by zkoch** [comment]
@ianbjacobs during the F2F, we decided to keep this a note, correct? Or did we get closure here?

**Comment by ianbjacobs** [comment]
Yes, we decided to keep it a NOTE. Please update the status section (via respec flags I believe) accordingly.

Thanks!

Ian

**Comment by marcoscaceres** [comment]
I'm still of two minds about this because we need this for the PR API (and possibly for the Payment Handler API too). That is, in both those aforementioned specs, these objects MAY be returned - putting conformance requirements on this particular spec. 

Even if this spec is not mentioned in the PR spec, user agents still need to produce objects that conform to this specification when "basic-card" is used.  

Thus, I I feel this spec needs to be on the Rec track.

**Comment by ianbjacobs** [comment]
@adrianba, I recall that you were a proponent of Note. Can you weigh in on this topic and whether this perspective from @marcoscaceres is new enough information that we should re-open the (twice closed) issue? Thanks!
