### ISSUE TITLE
Unclear what happens when there are duplicates?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webpayments-methods-card#36]
Given: 

```JS
new PaymentRequest(
  [
    {
      supportedMethods: "basic-card",
      data: {
        supportedTypes: ["debit"],
        supportedNetworks: ["visa", "amex"],
      },
    },
    {
      supportedMethods: "basic-card",
      data: {
        supportedNeworks: ["amex", "mastercard"],
      },
    },
    {
      supportedMethods: "basic-card",
    },
    {
      supportedMethods: "basic-card",
      data: {
         supportedTypes: ["credit"],
      }
    },
  ],
  details
);
```

What does that mean?

**Comment by marcoscaceres** [comment]
Fixed up example above.

**Comment by zkoch** [comment]
Is it unclear? My assumption is we treat each of them as their own tuple and run through the algorithm as written. Is there a part that's problematic?

**Comment by marcoscaceres** [comment]
@zkoch, when we show the sheet, which one wins or should the values be merged? That's unclear to me.

**Comment by zkoch** [comment]
I think the answer is "first one that matches". I don't think we merge anything.

**Comment by marcoscaceres** [comment]
Ok, we need to add that to the spec :) As per #34

**Comment by adrianhopebailie** [comment]
Maybe I am misunderstanding but the sheet doesn't show items from this list. 

The browser uses this list to establish the set of supported methods (and possibly filters for those methods) from the merchant. It compares that to the set of supported methods from all payment handlers (including the built-in `basic-card` handler) and shows a list of payment handlers (and possibly instruments) that can be used.

What is not clear is, if there is a payment method with filters (e.g. `supportedTypes: ["debit"]`) but another with the same identifier and no filters (implying all types are supported in this case) does that mean the filters are ignored.

If so, the example you provide above should be equivalent to:

```javascript
new PaymentRequest(
  [
    {
      supportedMethods: "basic-card",
    }
  ],
  details
);
```

..because when the browser gets to that tuple it will match on all handlers that handle `basic-card`.

So I think @zkoch is correct that the browser does nothing special for duplicates.

In fact, I think it is important that it does behave as currently written because a merchant may wish to use a request like this:

```javascript
new PaymentRequest(
  [
    {
      supportedMethods: "basic-card",
      data: {
        supportedTypes: ["debit"],
        supportedNetworks: ["visa", "amex"],
      }
    },
    {
      supportedMethods: "basic-card",
      data: {
         supportedTypes: ["credit"],
      }
    },
  ],
  details
);
```
...implying, I accept credit cards from all networks but debit cards only from VISA and Mastercard.

**Comment by marcoscaceres** [comment]
This belongs in the PR spec. Will reopen there.
